
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  5 2025 13:20:49 IST (Nov  5 2025 07:50:49 UTC)

// Verification Directory fv/KeyPadInterpreter 

module KeyPadInterpreter(Clock, ResetButton, KeyRead, RowDataIn,
     KeyReady, DataOut, ColDataOut, PressCount);
  input Clock, ResetButton, KeyRead;
  input [3:0] RowDataIn;
  output KeyReady;
  output [3:0] DataOut, ColDataOut, PressCount;
  wire Clock, ResetButton, KeyRead;
  wire [3:0] RowDataIn;
  wire KeyReady;
  wire [3:0] DataOut, ColDataOut, PressCount;
  wire [3:0] KeyCode;
  wire LFSRFlg, LFSRRst;
  PulseCounter Count(ResetButton, Clock, KeyReady, PressCount);
  KeyPadDecoder Decoder(KeyCode, DataOut);
  LFSR25000 LFSR(Clock, LFSRRst, LFSRFlg);
  KeyPadScanner Scanner(ResetButton, Clock, RowDataIn, ColDataOut,
       LFSRRst, LFSRFlg, KeyCode, KeyReady, KeyRead);
endmodule

