
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  5 2025 16:23:58 IST (Nov  5 2025 10:53:58 UTC)

// Verification Directory fv/top 

module top(clk, reset, col, row, keycode, keyValid);
  input clk, reset;
  input [3:0] col;
  output [3:0] row;
  output [7:0] keycode;
  output keyValid;
  wire clk, reset;
  wire [3:0] col;
  wire [3:0] row;
  wire [7:0] keycode;
  wire keyValid;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_11, n_12, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_37, n_38, n_45, n_46, n_47;
  DFFQX2 \row_reg[3] (.CK (clk), .D (n_38), .Q (row[3]));
  NAND2X1 g478__2398(.A (n_14), .B (n_32), .Y (n_38));
  OAI2BB1X1 g487__5107(.A0N (n_35), .A1N (row[2]), .B0 (n_34), .Y
       (n_37));
  DFFQX2 \row_reg[0] (.CK (clk), .D (n_47), .Q (row[0]));
  NAND3X2 g503__4319(.A (n_27), .B (row[3]), .C (n_31), .Y (n_34));
  OAI2BB1X1 g488__8428(.A0N (n_35), .A1N (row[1]), .B0 (n_26), .Y
       (n_33));
  XNOR2X1 g489__5526(.A (row[3]), .B (n_31), .Y (n_32));
  DFFQXL \keycode_reg[3] (.CK (clk), .D (n_30), .Q (keycode[3]));
  DFFQXL \keycode_reg[0] (.CK (clk), .D (n_29), .Q (keycode[0]));
  DFFQXL \keycode_reg[4] (.CK (clk), .D (n_25), .Q (keycode[4]));
  DFFQXL \keycode_reg[1] (.CK (clk), .D (n_21), .Q (keycode[1]));
  DFFQXL \keycode_reg[7] (.CK (clk), .D (n_22), .Q (keycode[7]));
  DFFQXL \keycode_reg[2] (.CK (clk), .D (n_19), .Q (keycode[2]));
  DFFQXL \keycode_reg[5] (.CK (clk), .D (n_24), .Q (keycode[5]));
  DFFQXL \keycode_reg[6] (.CK (clk), .D (n_20), .Q (keycode[6]));
  NOR2XL g494__6783(.A (reset), .B (n_18), .Y (n_30));
  NOR2XL g498__3680(.A (reset), .B (n_17), .Y (n_29));
  NAND3X1 g502__2802(.A (n_27), .B (n_23), .C (n_3), .Y (n_26));
  DFFQXL keyValid_reg(.CK (clk), .D (n_45), .Q (keyValid));
  NOR2XL g495__1705(.A (reset), .B (n_12), .Y (n_25));
  NOR2XL g496__5122(.A (reset), .B (n_11), .Y (n_24));
  AND2X6 g509__8246(.A (n_23), .B (n_2), .Y (n_31));
  NOR2XL g500__7098(.A (reset), .B (n_6), .Y (n_22));
  NOR2XL g499__6131(.A (reset), .B (n_8), .Y (n_21));
  NOR2XL g497__1881(.A (reset), .B (n_9), .Y (n_20));
  NOR2XL g493__5115(.A (reset), .B (n_7), .Y (n_19));
  MXI2XL g510__7482(.A (keycode[3]), .B (row[3]), .S0 (n_16), .Y
       (n_18));
  MXI2XL g511__4733(.A (keycode[0]), .B (row[0]), .S0 (n_16), .Y
       (n_17));
  NOR4X1 g504__6161(.A (n_16), .B (row[2]), .C (n_0), .D (row[3]), .Y
       (n_15));
  AOI2BB1X1 g505__9315(.A0N (n_16), .A1N (n_5), .B0 (reset), .Y (n_14));
  MXI2XL g512__2883(.A (col[0]), .B (keycode[4]), .S0 (n_46), .Y
       (n_12));
  MXI2XL g513__2346(.A (col[1]), .B (keycode[5]), .S0 (n_46), .Y
       (n_11));
  MXI2XL g514__1666(.A (col[2]), .B (keycode[6]), .S0 (n_46), .Y (n_9));
  MXI2XL g507__7410(.A (row[1]), .B (keycode[1]), .S0 (n_46), .Y (n_8));
  MXI2XL g508__6417(.A (row[2]), .B (keycode[2]), .S0 (n_46), .Y (n_7));
  MXI2XL g515__5477(.A (col[3]), .B (keycode[7]), .S0 (n_46), .Y (n_6));
  NOR2X2 g517__2398(.A (n_16), .B (row[1]), .Y (n_23));
  NOR2XL g516__5107(.A (reset), .B (n_46), .Y (n_35));
  INVX1 g518(.A (n_46), .Y (n_16));
  AOI21XL g520__4319(.A0 (row[1]), .A1 (row[2]), .B0 (row[0]), .Y
       (n_5));
  NOR3XL g521__8428(.A (col[1]), .B (col[0]), .C (col[2]), .Y (n_4));
  NOR2X1 g523__5526(.A (row[3]), .B (n_2), .Y (n_3));
  NOR2X2 g522__6783(.A (reset), .B (row[0]), .Y (n_27));
  NOR2BX1 g2(.AN (n_16), .B (reset), .Y (n_45));
  DFFX2 \row_reg[2] (.CK (clk), .D (n_37), .Q (row[2]), .QN (n_2));
  DFFX2 \row_reg[1] (.CK (clk), .D (n_33), .Q (row[1]), .QN (n_0));
  NOR2BX1 g544(.AN (n_4), .B (col[3]), .Y (n_46));
  AO22XL g545(.A0 (n_35), .A1 (row[0]), .B0 (n_27), .B1 (n_15), .Y
       (n_47));
endmodule

