
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov  5 2025 12:45:21 IST (Nov  5 2025 07:15:21 UTC)

// Verification Directory fv/top 

module top(clk, rst, rows, cols, key);
  input clk, rst;
  output [3:0] key;
  inout [3:0] rows, cols;
  wire clk, rst;
  wire [3:0] key;
  wire [3:0] rows, cols;
  wire [2:0] state;
  wire \drive_cols[0]_276 , \drive_rows[0]_272 , n_13, n_22, n_25,
       n_27, n_30, n_31;
  wire n_33, n_38, n_95, n_99, n_170, n_262, n_296, n_303;
  wire n_320, n_322, n_323, n_396, n_398, n_634, n_646, n_647;
  wire n_651, n_672, n_674, n_675, n_677, n_691, n_692, n_708;
  wire n_710, n_720, n_732, n_733, n_734, n_735, n_740, n_749;
  wire n_760, n_761, n_764, n_765, n_770, n_773, n_774, n_775;
  wire n_776, n_798, n_801, n_804, n_808, n_821, n_823, n_827;
  wire n_828, n_829, n_833, n_838, n_839, n_840, n_841, n_843;
  wire n_844, n_845, n_860, n_861, n_862, n_886, n_894, n_895;
  wire n_898, n_920, n_922, n_923, n_924, n_925, n_950, n_952;
  wire n_953, n_954, n_959, n_960, n_962, n_969, n_971, n_976;
  wire n_989, n_992, n_1005, n_1006, n_1007, n_1009, n_1010, n_1013;
  wire n_1014, n_1015, n_1041, n_1043;
  assign key[0] = 1'b0;
  assign key[1] = 1'b0;
  assign key[2] = 1'b0;
  assign key[3] = 1'b0;
  DFFRHQX4 \state_reg[0] (.RN (n_860), .CK (clk), .D (n_829), .Q
       (state[0]));
  DFFRHQX4 \state_reg[1] (.RN (n_860), .CK (clk), .D (n_954), .Q
       (state[1]));
  NOR2X4 g901__2398(.A (n_1043), .B (n_31), .Y (n_38));
  DFFSHQX4 \drive_cols_reg[0]160 (.SN (n_860), .CK (clk), .D (n_845),
       .Q (\drive_cols[0]_276 ));
  TBUFX1 g123__8428(.A (1'b0), .OE (n_646), .Y (n_33));
  NOR2X4 g904__6783(.A (cols[3]), .B (n_25), .Y (n_31));
  NOR2X4 g903__3680(.A (cols[1]), .B (n_22), .Y (n_30));
  NOR2X4 g906__1705(.A (cols[0]), .B (n_95), .Y (n_27));
  INVX3 g907(.A (cols[2]), .Y (n_25));
  INVX3 g910(.A (cols[0]), .Y (n_22));
  DFFSHQX4 \drive_rows_reg[0]156 (.SN (n_860), .CK (clk), .D (n_862),
       .Q (\drive_rows[0]_272 ));
  DFFRHQX4 \state_reg[2] (.RN (n_860), .CK (clk), .D (n_1007), .Q
       (state[2]));
  NAND2X4 g865__2398(.A (n_808), .B (n_962), .Y (n_13));
  INVX4 fopt925(.A (cols[1]), .Y (n_95));
  INVX6 fopt927(.A (rows[0]), .Y (n_99));
  NAND2BX2 g861__978(.AN (n_13), .B (n_749), .Y (n_170));
  INVX4 g447(.A (rows[3]), .Y (n_262));
  TBUFX3 g124__5526(.A (1'b0), .OE (n_646), .Y (n_296));
  NAND2X8 g60(.A (rows[0]), .B (rows[2]), .Y (n_303));
  NAND2X8 g29(.A (rows[2]), .B (n_262), .Y (n_320));
  INVX4 g30(.A (n_322), .Y (n_323));
  NOR2X6 g31(.A (n_840), .B (n_99), .Y (n_322));
  NAND2X8 g51(.A (cols[0]), .B (cols[1]), .Y (n_396));
  OAI21X4 g18(.A0 (rows[2]), .A1 (rows[0]), .B0 (rows[3]), .Y (n_634));
  TBUFX3 g125__4319(.A (1'b0), .OE (n_646), .Y (n_647));
  INVX8 g3(.A (\drive_rows[0]_272 ), .Y (n_646));
  INVX2 fopt31(.A (n_749), .Y (n_651));
  NAND2X6 g8(.A (cols[3]), .B (cols[2]), .Y (n_398));
  INVX1 g70(.A (n_675), .Y (n_672));
  INVX8 g68(.A (n_976), .Y (n_674));
  NOR2X1 g1317(.A (n_749), .B (n_808), .Y (n_677));
  NOR2X8 g1325(.A (n_960), .B (n_989), .Y (n_691));
  INVX6 g1327(.A (n_1006), .Y (n_692));
  NAND2X6 g1338(.A (n_840), .B (n_303), .Y (n_708));
  INVX1 g240(.A (n_894), .Y (n_720));
  NOR3X4 g315(.A (n_733), .B (n_720), .C (n_734), .Y (n_735));
  NOR3X6 g317(.A (n_732), .B (n_323), .C (n_320), .Y (n_733));
  NAND2X4 g318(.A (n_962), .B (n_651), .Y (n_732));
  NOR3X8 g316(.A (n_732), .B (n_634), .C (n_839), .Y (n_734));
  NOR2X6 g124(.A (n_396), .B (n_38), .Y (n_740));
  TBUFX3 g127__6260(.A (1'b0), .OE (n_760), .Y (n_761));
  INVX6 g7(.A (\drive_cols[0]_276 ), .Y (n_760));
  TBUFX6 g129__5107(.A (1'b0), .OE (n_760), .Y (n_764));
  TBUFX6 g130__7410(.A (1'b0), .OE (n_760), .Y (n_765));
  AO21X4 g125(.A0 (n_770), .A1 (n_651), .B0 (n_773), .Y (n_774));
  NOR2X2 g126(.A (n_960), .B (n_675), .Y (n_773));
  NAND2X6 g1361(.A (n_773), .B (n_672), .Y (n_775));
  TBUFX3 g128__6417(.A (1'b0), .OE (n_760), .Y (n_776));
  NAND2X8 g361(.A (n_774), .B (n_971), .Y (n_804));
  NOR2X4 g370(.A (n_749), .B (n_675), .Y (n_798));
  NOR2X4 g369(.A (cols[2]), .B (cols[3]), .Y (n_801));
  BUFX6 fopt1374(.A (n_992), .Y (n_808));
  TBUFX20 g120__6161(.A (n_761), .OE (n_920), .Y (cols[3]));
  INVX16 fopt60(.A (state[0]), .Y (n_710));
  INVX4 fopt1385(.A (n_710), .Y (n_749));
  OAI21X4 g207(.A0 (n_828), .A1 (n_804), .B0 (n_735), .Y (n_829));
  NOR4X6 g208(.A (n_821), .B (n_823), .C (n_1009), .D (n_827), .Y
       (n_828));
  NAND2X4 g216(.A (cols[3]), .B (cols[2]), .Y (n_821));
  NOR2X6 g215(.A (n_396), .B (n_398), .Y (n_827));
  TBUFX20 g119__1666(.A (n_833), .OE (n_886), .Y (rows[0]));
  TBUFX3 g126__6260(.A (1'b0), .OE (n_646), .Y (n_833));
  TBUFX20 g118__5477(.A (n_647), .OE (n_691), .Y (rows[1]));
  TBUFX20 g117__7410(.A (n_296), .OE (n_691), .Y (rows[2]));
  NAND2X8 g33(.A (n_838), .B (n_708), .Y (n_839));
  NAND3X6 g34(.A (rows[1]), .B (rows[2]), .C (rows[0]), .Y (n_838));
  INVX12 g1396(.A (rows[1]), .Y (n_840));
  INVXL g36(.A (n_886), .Y (n_841));
  TBUFX4 g1__6417(.A (n_33), .OE (n_886), .Y (rows[3]));
  NAND2X8 g11(.A (n_843), .B (n_844), .Y (n_845));
  AND2X6 g12(.A (n_841), .B (n_170), .Y (n_843));
  INVX20 g13(.A (rst), .Y (n_844));
  INVX1 g10(.A (rst), .Y (n_860));
  NAND2X8 g1408(.A (n_692), .B (n_861), .Y (n_862));
  INVX20 g1409(.A (rst), .Y (n_861));
  NOR2X8 g1432(.A (n_675), .B (n_925), .Y (n_886));
  INVX1 g1444(.A (n_894), .Y (n_895));
  NAND3X4 g32(.A (n_749), .B (n_808), .C (n_960), .Y (n_894));
  INVX4 g1447(.A (n_170), .Y (n_898));
  NOR3X6 g1458(.A (n_710), .B (n_959), .C (n_675), .Y (n_920));
  NOR3X8 g1460(.A (n_710), .B (n_959), .C (n_992), .Y (n_922));
  NOR3X8 g1462(.A (n_710), .B (n_992), .C (n_959), .Y (n_923));
  NOR3X6 g1463(.A (n_710), .B (n_959), .C (n_675), .Y (n_924));
  NAND2X8 g1464(.A (n_959), .B (n_710), .Y (n_925));
  NAND3X4 g77(.A (n_950), .B (n_952), .C (n_953), .Y (n_954));
  NOR3X4 g78(.A (n_895), .B (n_1006), .C (n_898), .Y (n_950));
  NAND2X4 g80(.A (n_1005), .B (n_1010), .Y (n_952));
  NAND2X6 g79(.A (n_1005), .B (n_740), .Y (n_953));
  INVX3 fopt4(.A (n_960), .Y (n_962));
  INVX16 fopt5(.A (n_959), .Y (n_960));
  INVX16 fopt6(.A (state[1]), .Y (n_959));
  NAND2X6 g1494(.A (n_969), .B (n_1015), .Y (n_971));
  NOR3X4 g1495(.A (n_396), .B (n_801), .C (n_798), .Y (n_969));
  BUFX6 g1497(.A (n_1014), .Y (n_823));
  NOR2X8 g1500(.A (cols[0]), .B (cols[1]), .Y (n_976));
  TBUFX20 g121__5115(.A (n_764), .OE (n_923), .Y (cols[1]));
  TBUFX20 g122__7482(.A (n_765), .OE (n_922), .Y (cols[0]));
  INVX16 g1510(.A (state[2]), .Y (n_770));
  NAND2X8 g1512(.A (n_770), .B (n_710), .Y (n_989));
  INVX12 g1513(.A (n_770), .Y (n_675));
  INVX16 g1515(.A (n_770), .Y (n_992));
  AND2X4 g2(.A (n_962), .B (n_749), .Y (n_1005));
  AND2X4 g1524(.A (n_960), .B (n_677), .Y (n_1006));
  OAI21XL g1525(.A0 (n_651), .A1 (n_962), .B0 (n_13), .Y (n_1007));
  OR2X6 g1527(.A (n_798), .B (n_801), .Y (n_1009));
  AOI2BB1X4 g1528(.A0N (n_27), .A1N (n_30), .B0 (n_821), .Y (n_1010));
  NOR2X4 g1530(.A (n_1013), .B (n_1014), .Y (n_1015));
  INVX8 g1531(.A (n_398), .Y (n_1013));
  NOR2X8 g1532(.A (n_775), .B (n_674), .Y (n_1014));
  NOR2X4 g1558(.A (n_1041), .B (cols[2]), .Y (n_1043));
  INVX4 g1559(.A (cols[3]), .Y (n_1041));
  TBUFX20 g2__4733(.A (n_776), .OE (n_924), .Y (cols[2]));
endmodule

